language: node_js
node_js: node
before_install:
- npm i -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
matrix:
  include:
    - env: INSTALL_TYPE="locked"
    - env: INSTALL_TYPE="canary"
install: npm run install-$INSTALL_TYPE
addons:
  firefox: '51.0'
deploy:
  provider: npm
  email: core@donejs.com
  api_key:
    secure: >-
      KhGyXdmpI5IQOA3IUucml1f8IaAenyavZcs9mE5JJm91N9iZQrhRWQqmkubG6mOXNVeT01hVwntSgdeSTap1zkTGrlz0/N2N4D9mMxd9CiRgs77Op5ekUF0saC95psI0Ke6i//16g4+5iFncnB/6q2OKafE+RT/nk5lO/GcX2+YzfVfYhvXs2+xzLun2mUTAeu3Labfo1DB4INce7nTAorQoKK+fbiWSwGNBFUiT5yzPsLRxzW8+8Il0/eu6KIRqro1Udyx3/40xEMBG3tgj4WBrAe846YtX6dRF/DHjggnEq+E2HJBSkItokAv04RTN/X0QQvs9aPrdGX2AWuoeAQnw5459eMLQUYENOtFFTEzhrLduiiOglaUw8QoPavpylaqCAsMRR/aMBxZ42mOo2KRIT26YN/kv4qlSNIZcXvtOeT2TmD/ctcWdnAC4ZQS0uEc29RRTeSmDPWhBv9Mdpljy/5zMs6O6+bKCaFqjn06ZHYCffjg6dAafxFneL5mjtDzUIrp7/5v4UzEiXzEZWj/S9AkqzO5tUiknqB2/3FP3As+B4XM7gAO4RbcA8XUQfOyJu3oSzPL3cp7tQ9Oiut/DOCFHFbsf8qLi0sovwNteheZ+M5XOZzH54G55pkUhKewno9aB9EB+hHlqAy54Gp1i3V/efD3xiasF/XzB+jk=
  'on':
    tags: true
    repo: canjs/can-event-dom-radiochange
dist: xenial
services:
  - xvfb
