language: node_js
node_js: node
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm i -g greenkeeper-lockfile@1"
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
matrix:
  include:
    - env: INSTALL_TYPE="locked"
    - env: INSTALL_TYPE="canary"
install: npm run install-$INSTALL_TYPE
addons:
  firefox: "51.0"
